export const arraisAmadorQuestions = [
  {
    id: 7001,
    subject: 'arrais-amador',
    topic: 'termos-nauticos',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Em uma embarcação, a parte dianteira é chamada de:',
    options: { A: 'Popa', B: 'Boreste', C: 'Proa', D: 'Bombordo', E: 'Convés' },
    correct: 'C',
    explanation: 'Proa é a parte da frente da embarcação. Popa é a parte de trás.',
    conceptKey: 'ara.termos.proa',
    difficulty: 'easy',
  },
  {
    id: 7002,
    subject: 'arrais-amador',
    topic: 'termos-nauticos',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'O lado direito da embarcação, olhando-se da popa para a proa, chama-se:',
    options: { A: 'Bombordo', B: 'Boreste', C: 'Alheta', D: 'Través', E: 'Convés' },
    correct: 'B',
    explanation: 'Boreste é o lado direito da embarcação no sentido popa-proa.',
    conceptKey: 'ara.termos.boreste',
    difficulty: 'easy',
  },
  {
    id: 7003,
    subject: 'arrais-amador',
    topic: 'termos-nauticos',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'O lado esquerdo da embarcação, olhando-se da popa para a proa, chama-se:',
    options: { A: 'Bombordo', B: 'Boreste', C: 'Vante', D: 'Alheta', E: 'Costado' },
    correct: 'A',
    explanation: 'Bombordo é o lado esquerdo da embarcação no sentido popa-proa.',
    conceptKey: 'ara.termos.bombordo',
    difficulty: 'easy',
  },
  {
    id: 7004,
    subject: 'arrais-amador',
    topic: 'termos-nauticos',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'A parte traseira da embarcação é chamada de:',
    options: { A: 'Proa', B: 'Popa', C: 'Vante', D: 'Bochecha', E: 'Amura' },
    correct: 'B',
    explanation: 'Popa é a parte de trás da embarcação.',
    conceptKey: 'ara.termos.popa',
    difficulty: 'easy',
  },
  {
    id: 7005,
    subject: 'arrais-amador',
    topic: 'partes-da-embarcacao',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'O piso superior ou cobertura principal da embarcação é denominado:',
    options: { A: 'Costado', B: 'Convés', C: 'Casario', D: 'Porão', E: 'Mastro' },
    correct: 'B',
    explanation: 'Convés é a cobertura principal ou piso superior da embarcação.',
    conceptKey: 'ara.partes.conves',
    difficulty: 'easy',
  },
  {
    id: 7006,
    subject: 'arrais-amador',
    topic: 'direcoes-relativas',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'A direção perpendicular ao rumo da embarcação, por um dos lados, é chamada de:',
    options: { A: 'Vante', B: 'Alheta', C: 'Través', D: 'Amura', E: 'Popa' },
    correct: 'C',
    explanation: 'Través é a direção perpendicular ao rumo, por boreste ou bombordo.',
    conceptKey: 'ara.direcoes.traves',
    difficulty: 'easy',
  },
  {
    id: 7007,
    subject: 'arrais-amador',
    topic: 'marinharia',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'O nó utilizado para unir duas espias de mesma bitola é, em geral:',
    options: { A: 'Lais de guia', B: 'Volta do fiel', C: 'Nó direito', D: 'Catau', E: 'Balso pelo seio' },
    correct: 'C',
    explanation: 'O nó direito é uma união simples e clássica para cabos de mesma bitola.',
    conceptKey: 'ara.nos.no_direito',
    difficulty: 'medium',
  },
  {
    id: 7008,
    subject: 'arrais-amador',
    topic: 'marinharia',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'A volta usada para prender rapidamente uma espia a um cabeço ou argola é chamada de:',
    options: { A: 'Volta do fiel', B: 'Nó de escota', C: 'Nó de correr', D: 'Lais de guia', E: 'Falcaça' },
    correct: 'A',
    explanation: 'A volta do fiel é muito usada para prender espias com segurança e rapidez.',
    conceptKey: 'ara.nos.volta_do_fiel',
    difficulty: 'easy',
  },
  {
    id: 7009,
    subject: 'arrais-amador',
    topic: 'marinharia',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'O lais de guia é especialmente útil para:',
    options: { A: 'Encurtar um cabo', B: 'Fazer uma alça fixa', C: 'Unir dois cabos finos', D: 'Amarrar velas', E: 'Aumentar a elasticidade do cabo' },
    correct: 'B',
    explanation: 'O lais de guia forma uma alça fixa que não corre.',
    conceptKey: 'ara.nos.lais_de_guia',
    difficulty: 'medium',
  },
  {
    id: 7010,
    subject: 'arrais-amador',
    topic: 'marinharia',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Uma espia usada para amarrar a embarcação ao cais é chamada de:',
    options: { A: 'Adriça', B: 'Escota', C: 'Amarra', D: 'Espia', E: 'Brandal' },
    correct: 'D',
    explanation: 'Espia é o cabo usado para prender a embarcação ao cais ou a uma boia.',
    conceptKey: 'ara.marinharia.espia',
    difficulty: 'easy',
  },
  {
    id: 7011,
    subject: 'arrais-amador',
    topic: 'fundeio',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Ao fundear, uma boa prática é escolher local com profundidade compatível, abrigo e fundo que favoreça a pega da âncora. Isso visa principalmente:',
    options: { A: 'Aumentar o consumo', B: 'Reduzir o borneio e garantir segurança', C: 'Facilitar a pintura do casco', D: 'Eliminar a influência do vento', E: 'Dispensar vigilância' },
    correct: 'B',
    explanation: 'A escolha correta do local de fundeio ajuda a garantir que a âncora unhe e a embarcação permaneça segura.',
    conceptKey: 'ara.fundeio.escolha_local',
    difficulty: 'medium',
  },
  {
    id: 7012,
    subject: 'arrais-amador',
    topic: 'fundeio',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Após fundear, a verificação de que a âncora realmente agarrou o fundo é importante para:',
    options: { A: 'Dispensar vigia', B: 'Evitar que a embarcação garre', C: 'Melhorar o sinal do GNSS', D: 'Diminuir o calado', E: 'Aumentar a velocidade' },
    correct: 'B',
    explanation: 'Se a âncora não agarrou adequadamente, a embarcação pode garrear e derivar.',
    conceptKey: 'ara.fundeio.garreio',
    difficulty: 'easy',
  },
  {
    id: 7013,
    subject: 'arrais-amador',
    topic: 'atracacao',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Durante uma atracação, o procedimento mais seguro é aproximar-se do cais com:',
    options: { A: 'Alta velocidade', B: 'Velocidade compatível e controle', C: 'Motor desligado', D: 'Somente à deriva', E: 'Máquina avante toda força' },
    correct: 'B',
    explanation: 'Atracações exigem baixa velocidade e bom controle para evitar abalroamentos e danos.',
    conceptKey: 'ara.atracacao.velocidade',
    difficulty: 'easy',
  },
  {
    id: 7014,
    subject: 'arrais-amador',
    topic: 'desatracacao',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Antes de desatracar, o condutor deve verificar principalmente:',
    options: { A: 'Se há combustível, espias, defensas e condições do entorno', B: 'Somente a cor do casco', C: 'A temperatura da água', D: 'Se o rádio está desligado', E: 'A quantidade de pintura a bordo' },
    correct: 'A',
    explanation: 'A desatracação segura depende de preparação da embarcação e observação do ambiente ao redor.',
    conceptKey: 'ara.desatracacao.preparo',
    difficulty: 'easy',
  },
  {
    id: 7015,
    subject: 'arrais-amador',
    topic: 'pegar-boia',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Ao pegar uma boia de amarração, a aproximação deve ser feita de modo controlado, preferencialmente:',
    options: { A: 'Com velocidade elevada para reduzir tempo de manobra', B: 'Sem observar vento e corrente', C: 'Considerando vento e corrente e com baixa velocidade', D: 'Com pessoas nas bordas da embarcação', E: 'Com marcha à ré contínua' },
    correct: 'C',
    explanation: 'Vento e corrente influenciam a aproximação. A baixa velocidade aumenta o controle.',
    conceptKey: 'ara.boia.aproximacao',
    difficulty: 'medium',
  },
  {
    id: 7016,
    subject: 'arrais-amador',
    topic: 'homem-ao-mar',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Em uma situação de homem ao mar, a ação imediata mais importante é:',
    options: { A: 'Acelerar para retornar mais rápido', B: 'Manter contato visual e iniciar o resgate', C: 'Desligar todos os equipamentos', D: 'Abandonar a embarcação', E: 'Mandar todos sentarem sem agir' },
    correct: 'B',
    explanation: 'Manter contato visual com a vítima é essencial para não perder sua posição e iniciar o resgate com segurança.',
    conceptKey: 'ara.homem_ao_mar.contato_visual',
    difficulty: 'easy',
  },
  {
    id: 7017,
    subject: 'arrais-amador',
    topic: 'homem-ao-mar',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Ao perceber uma queda n’água, é recomendável lançar imediatamente um objeto flutuante porque isso:',
    options: { A: 'Substitui o resgate', B: 'Aumenta o alcance do rádio', C: 'Ajuda a manter a vítima apoiada e visível', D: 'Impede a ação do vento', E: 'Elimina risco de hipotermia' },
    correct: 'C',
    explanation: 'O objeto flutuante dá apoio à vítima e ajuda a marcar visualmente a posição.',
    conceptKey: 'ara.homem_ao_mar.objeto_flutuante',
    difficulty: 'easy',
  },
  {
    id: 7018,
    subject: 'arrais-amador',
    topic: 'preparacao-embarcacao',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Antes de sair para navegar, é fundamental verificar combustível, água, salvatagem e rota prevista. Esse conjunto faz parte do:',
    options: { A: 'Plano de abalroamento', B: 'Plano de navegação', C: 'Plano de docagem', D: 'Plano de emergência médica apenas', E: 'Plano de pintura' },
    correct: 'B',
    explanation: 'O plano de navegação reúne providências e verificações para uma saída segura.',
    conceptKey: 'ara.preparo.plano_navegacao',
    difficulty: 'easy',
  },
  {
    id: 7019,
    subject: 'arrais-amador',
    topic: 'preparacao-embarcacao',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Distribuir adequadamente pessoas e cargas a bordo ajuda principalmente a preservar:',
    options: { A: 'A cor da pintura', B: 'A estabilidade e o equilíbrio', C: 'O sinal do celular', D: 'A velocidade máxima sempre', E: 'A pressão atmosférica' },
    correct: 'B',
    explanation: 'Má distribuição de peso compromete a estabilidade e a segurança da embarcação.',
    conceptKey: 'ara.preparo.distribuicao_peso',
    difficulty: 'easy',
  },
  {
    id: 7020,
    subject: 'arrais-amador',
    topic: 'propulsao',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Em uma embarcação a motor com um único hélice, o governo em baixa velocidade exige atenção especial porque:',
    options: { A: 'O efeito do leme pode ser reduzido', B: 'O casco some da água', C: 'O GNSS para de funcionar', D: 'O eco bate no fundo', E: 'A âncora fica travada' },
    correct: 'A',
    explanation: 'Em baixa velocidade, o fluxo sobre o leme é menor, reduzindo seu efeito e exigindo mais antecipação nas manobras.',
    conceptKey: 'ara.propulsao.leme_baixa_velocidade',
    difficulty: 'medium',
  },
  {
    id: 7021,
    subject: 'arrais-amador',
    topic: 'propulsao',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'A marcha a ré em espaço limitado requer cuidado extra porque a embarcação pode apresentar:',
    options: { A: 'Resposta previsível idêntica à vante em qualquer casco', B: 'Maior dificuldade de governo e efeito diferente do hélice', C: 'Eliminação total da influência do vento', D: 'Impossibilidade de uso do leme', E: 'Aumento automático da estabilidade' },
    correct: 'B',
    explanation: 'Em marcha a ré, a resposta ao leme e os efeitos do hélice podem tornar a manobra menos intuitiva.',
    conceptKey: 'ara.propulsao.marcha_re',
    difficulty: 'medium',
  },
  {
    id: 7022,
    subject: 'arrais-amador',
    topic: 'classificacao-embarcacoes',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Uma embarcação miúda é, em regra, uma embarcação de pequeno porte usada em atividades locais ou de apoio. Essa classificação é importante porque:',
    options: { A: 'Dispensa qualquer regra de segurança', B: 'Influencia equipamentos e operação segura', C: 'Permite navegação sem habilitação', D: 'Elimina exigência de material de salvatagem', E: 'Substitui o RIPEAM' },
    correct: 'B',
    explanation: 'A classificação da embarcação influencia requisitos operacionais e de segurança.',
    conceptKey: 'ara.classificacao.embarcacoes',
    difficulty: 'easy',
  },
  {
    id: 7023,
    subject: 'arrais-amador',
    topic: 'incendio',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Para haver fogo, é necessária a presença dos elementos do chamado triângulo do fogo, que são:',
    options: { A: 'Água, ferro e ar', B: 'Calor, combustível e comburente', C: 'Combustível, vento e tinta', D: 'Água, calor e espuma', E: 'Combustível, óleo e fumaça' },
    correct: 'B',
    explanation: 'O triângulo do fogo é formado por calor, combustível e comburente (oxigênio).',
    conceptKey: 'ara.incendio.triangulo_fogo',
    difficulty: 'easy',
  },
  {
    id: 7024,
    subject: 'arrais-amador',
    topic: 'incendio',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'No combate a incêndio a bordo, conhecer o tipo de extintor adequado é importante porque:',
    options: { A: 'Todo extintor serve para qualquer fogo sem restrição', B: 'O agente extintor deve ser compatível com a classe do incêndio', C: 'Extintores só funcionam em terra', D: 'O extintor de água é sempre o melhor para eletricidade', E: 'O tipo de incêndio não influencia o combate' },
    correct: 'B',
    explanation: 'A compatibilidade do agente extintor com a classe do incêndio evita agravamento da situação e melhora a eficácia.',
    conceptKey: 'ara.incendio.tipo_extintor',
    difficulty: 'medium',
  },
  {
    id: 7025,
    subject: 'arrais-amador',
    topic: 'incendio',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Se ocorrer cheiro forte de combustível a bordo antes da partida do motor, o procedimento prudente é:',
    options: { A: 'Dar partida para testar mais rápido', B: 'Ignorar, pois é normal', C: 'Ventilar, verificar vazamentos e eliminar a causa antes de ligar', D: 'Acender uma luz de chama para procurar o vazamento', E: 'Aumentar a carga elétrica' },
    correct: 'C',
    explanation: 'Vapores inflamáveis representam alto risco. É preciso ventilar e localizar a origem do vazamento antes de ligar o motor.',
    conceptKey: 'ara.incendio.cheiro_combustivel',
    difficulty: 'medium',
  },
  {
    id: 7026,
    subject: 'arrais-amador',
    topic: 'primeiros-socorros',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Em um caso de hemorragia externa, a primeira providência costuma ser:',
    options: { A: 'Oferecer alimento', B: 'Comprimir o local e buscar ajuda', C: 'Molhar continuamente com água do mar', D: 'Aplicar gelo diretamente em ferida aberta profunda sempre', E: 'Ignorar se a vítima estiver consciente' },
    correct: 'B',
    explanation: 'A compressão direta é uma medida inicial importante para conter hemorragias externas.',
    conceptKey: 'ara.ps.hemorragia',
    difficulty: 'easy',
  },
  {
    id: 7027,
    subject: 'arrais-amador',
    topic: 'primeiros-socorros',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Em caso de queimadura térmica leve, a medida inicial recomendada é:',
    options: { A: 'Aplicar graxa ou óleo', B: 'Resfriar com água limpa e proteger o local', C: 'Romper bolhas', D: 'Aplicar combustível para desinfetar', E: 'Cobrir com pano seco quente' },
    correct: 'B',
    explanation: 'Resfriar a área com água limpa ajuda a reduzir a lesão e a dor. Não se deve aplicar substâncias inadequadas.',
    conceptKey: 'ara.ps.queimadura',
    difficulty: 'easy',
  },
  {
    id: 7028,
    subject: 'arrais-amador',
    topic: 'sobrevivencia',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Em situação de permanência na água fria, um risco importante é:',
    options: { A: 'Hipotermia', B: 'Desmagnetização do casco', C: 'Aumento do calado', D: 'Autoignição', E: 'Formação de ferrugem instantânea' },
    correct: 'A',
    explanation: 'A perda de calor corporal em água fria pode levar à hipotermia.',
    conceptKey: 'ara.sobrevivencia.hipotermia',
    difficulty: 'easy',
  },
  {
    id: 7029,
    subject: 'arrais-amador',
    topic: 'sobrevivencia',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'O uso correto do colete salva-vidas é importante porque ele:',
    options: { A: 'Substitui a embarcação', B: 'Ajuda a manter a flutuação e as vias aéreas fora d’água', C: 'Evita totalmente o frio', D: 'Elimina a necessidade de resgate', E: 'Dispensa saber nadar em qualquer situação' },
    correct: 'B',
    explanation: 'O colete salva-vidas auxilia a manter a pessoa flutuando e aumenta a chance de sobrevivência.',
    conceptKey: 'ara.sobrevivencia.colete',
    difficulty: 'easy',
  },
  {
    id: 7030,
    subject: 'arrais-amador',
    topic: 'salvatagem',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'A boia circular é usada principalmente para:',
    options: { A: 'Prender a âncora', B: 'Auxiliar no salvamento de uma pessoa na água', C: 'Medir a velocidade', D: 'Sinalizar profundidade', E: 'Substituir a defesa de cais' },
    correct: 'B',
    explanation: 'A boia circular é um equipamento de salvatagem para auxílio a pessoas na água.',
    conceptKey: 'ara.salvatagem.boia_circular',
    difficulty: 'easy',
  },
  {
    id: 7031,
    subject: 'arrais-amador',
    topic: 'salvatagem',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Artefatos pirotécnicos a bordo servem principalmente para:',
    options: { A: 'Iluminar permanentemente a cabine', B: 'Sinalização de emergência', C: 'Acender fogão de bordo', D: 'Aumentar o alcance do radar', E: 'Substituir lanterna' },
    correct: 'B',
    explanation: 'Pirotécnicos são usados para sinalizar emergência e facilitar localização e socorro.',
    conceptKey: 'ara.salvatagem.pirotecnicos',
    difficulty: 'easy',
  },
  {
    id: 7032,
    subject: 'arrais-amador',
    topic: 'salvatagem',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Antes de sair, conferir a palamenta obrigatória é importante porque:',
    options: { A: 'É mera formalidade sem impacto na segurança', B: 'Garante que o material essencial esteja disponível em caso de necessidade', C: 'Só importa em barcos de grande porte', D: 'Substitui o plano de navegação', E: 'É exigido apenas à noite' },
    correct: 'B',
    explanation: 'A palamenta reúne itens de segurança e apoio que podem ser críticos em emergências.',
    conceptKey: 'ara.salvatagem.palamenta',
    difficulty: 'easy',
  },
  {
    id: 7033,
    subject: 'arrais-amador',
    topic: 'instrumentos',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'A agulha magnética ou bússola é usada para:',
    options: { A: 'Medir profundidade', B: 'Indicar direção', C: 'Medir pressão atmosférica', D: 'Medir velocidade do vento', E: 'Transmitir mensagens' },
    correct: 'B',
    explanation: 'A bússola é um instrumento de direção.',
    conceptKey: 'ara.instrumentos.bussola',
    difficulty: 'easy',
  },
  {
    id: 7034,
    subject: 'arrais-amador',
    topic: 'instrumentos',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'O odômetro em uma embarcação indica, em geral:',
    options: { A: 'A posição geográfica', B: 'A temperatura da água', C: 'Distância/velocidade percorrida conforme o sistema adotado', D: 'A altura da maré', E: 'A direção do vento' },
    correct: 'C',
    explanation: 'O odômetro auxilia na indicação de distância ou velocidade percorrida conforme o equipamento.',
    conceptKey: 'ara.instrumentos.odometro',
    difficulty: 'medium',
  },
  {
    id: 7035,
    subject: 'arrais-amador',
    topic: 'instrumentos',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'O tacômetro informa ao condutor:',
    options: { A: 'A rotação do motor', B: 'A posição da âncora', C: 'A temperatura do ar', D: 'A profundidade', E: 'A intensidade da maré' },
    correct: 'A',
    explanation: 'Tacômetro é o instrumento que indica a rotação do motor.',
    conceptKey: 'ara.instrumentos.tacometro',
    difficulty: 'easy',
  },
  {
    id: 7036,
    subject: 'arrais-amador',
    topic: 'instrumentos',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'O anemômetro serve para medir:',
    options: { A: 'Profundidade', B: 'Velocidade do vento', C: 'Rotação do motor', D: 'Rumo verdadeiro', E: 'Velocidade da corrente' },
    correct: 'B',
    explanation: 'Anemômetro mede a velocidade do vento.',
    conceptKey: 'ara.instrumentos.anemometro',
    difficulty: 'easy',
  },
  {
    id: 7037,
    subject: 'arrais-amador',
    topic: 'instrumentos',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'O GNSS a bordo é usado principalmente para:',
    options: { A: 'Apagar incêndio', B: 'Determinar posição e auxiliar a navegação', C: 'Substituir o colete', D: 'Medir a pressão atmosférica', E: 'Dispensar vigia' },
    correct: 'B',
    explanation: 'GNSS fornece posição e auxilia o navegador no planejamento e acompanhamento da derrota.',
    conceptKey: 'ara.instrumentos.gnss',
    difficulty: 'easy',
  },
  {
    id: 7038,
    subject: 'arrais-amador',
    topic: 'instrumentos',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'O ecobatímetro é um equipamento usado para:',
    options: { A: 'Medir profundidade sob a quilha', B: 'Medir força do vento', C: 'Indicar rotação do motor', D: 'Fazer chamadas de socorro', E: 'Ler a pressão atmosférica' },
    correct: 'A',
    explanation: 'O ecobatímetro informa a profundidade, auxiliando a navegação segura.',
    conceptKey: 'ara.instrumentos.ecobatimetro',
    difficulty: 'easy',
  },
  {
    id: 7039,
    subject: 'arrais-amador',
    topic: 'meteorologia',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Consultar a previsão do tempo antes de sair é importante porque permite:',
    options: { A: 'Eliminar totalmente os riscos', B: 'Antecipar condições de vento, chuva e segurança da navegação', C: 'Dispensar material de salvatagem', D: 'Ignorar mudanças locais', E: 'Substituir o plano de navegação' },
    correct: 'B',
    explanation: 'A previsão do tempo ajuda a decidir se as condições são seguras e a se preparar adequadamente.',
    conceptKey: 'ara.meteo.previsao',
    difficulty: 'easy',
  },
  {
    id: 7040,
    subject: 'arrais-amador',
    topic: 'meteorologia',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'A aproximação de nuvens muito desenvolvidas verticalmente pode indicar:',
    options: { A: 'Tempo sempre estável', B: 'Possibilidade de pancadas, rajadas e trovoadas', C: 'Ausência de vento', D: 'Somente nevoeiro fraco', E: 'Correnteza mais forte' },
    correct: 'B',
    explanation: 'Nuvens com grande desenvolvimento vertical costumam estar associadas a instabilidade.',
    conceptKey: 'ara.meteo.nuvens_instabilidade',
    difficulty: 'easy',
  },
  {
    id: 7041,
    subject: 'arrais-amador',
    topic: 'meteorologia',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Uma alteração brusca do tempo durante a navegação exige do condutor:',
    options: { A: 'Ignorar a mudança se a embarcação for pequena', B: 'Reavaliar rota, abrigo e segurança da tripulação', C: 'Aumentar a velocidade sempre', D: 'Desligar a iluminação de navegação', E: 'Retirar coletes para maior mobilidade' },
    correct: 'B',
    explanation: 'Mudanças bruscas pedem reavaliação imediata das condições de navegação e da segurança a bordo.',
    conceptKey: 'ara.meteo.mudanca_tempo',
    difficulty: 'medium',
  },
  {
    id: 7042,
    subject: 'arrais-amador',
    topic: 'mares',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Conhecer o comportamento das marés é importante porque a maré pode alterar:',
    options: { A: 'A profundidade disponível e as condições de navegação', B: 'A cor da boia lateral', C: 'O comprimento do casco', D: 'A potência do VHF', E: 'O número de coletes obrigatórios' },
    correct: 'A',
    explanation: 'A maré influencia a profundidade, correntes e a segurança de entradas, saídas e passagens rasas.',
    conceptKey: 'ara.mare.importancia',
    difficulty: 'easy',
  },
  {
    id: 7043,
    subject: 'arrais-amador',
    topic: 'mares',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'A tábua de marés é usada para:',
    options: { A: 'Identificar o tipo de tinta do casco', B: 'Consultar horários e alturas de maré', C: 'Medir a velocidade do vento', D: 'Determinar a rotação do motor', E: 'Fazer chamada de urgência' },
    correct: 'B',
    explanation: 'A tábua de marés informa horários e alturas previstos, auxiliando o planejamento da navegação.',
    conceptKey: 'ara.mare.tabua',
    difficulty: 'easy',
  },
  {
    id: 7044,
    subject: 'arrais-amador',
    topic: 'mares',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Ao planejar a passagem por um local raso, a consulta às tábuas de marés ajuda a evitar:',
    options: { A: 'A comunicação no canal 16', B: 'O risco de tocar o fundo', C: 'A formação de nevoeiro', D: 'O uso de coletes', E: 'O aparecimento de boias' },
    correct: 'B',
    explanation: 'Com a maré mais baixa, a profundidade disponível pode ser insuficiente, aumentando o risco de encalhe.',
    conceptKey: 'ara.mare.local_raso',
    difficulty: 'medium',
  },
  {
    id: 7045,
    subject: 'arrais-amador',
    topic: 'ripeam-luzes',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Uma embarcação fundeada à noite deve mostrar, em regra:',
    options: { A: 'Somente luz verde', B: 'Somente luz encarnada', C: 'Luz branca visível em todo o horizonte', D: 'Duas luzes amarelas', E: 'Nenhuma luz' },
    correct: 'C',
    explanation: 'A luz branca de fundeio indica a presença da embarcação parada pela âncora.',
    conceptKey: 'ara.ripeam.fundeio_luz',
    difficulty: 'easy',
  },
  {
    id: 7046,
    subject: 'arrais-amador',
    topic: 'ripeam-luzes',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Embarcações de propulsão mecânica em movimento exibem, entre outras, luzes de bordo nas cores:',
    options: { A: 'Azul e amarela', B: 'Encarnada a bombordo e verde a boreste', C: 'Branca e amarela nos bordos', D: 'Duas verdes', E: 'Duas encarnadas' },
    correct: 'B',
    explanation: 'As luzes de bordo são encarnada no bombordo e verde no boreste.',
    conceptKey: 'ara.ripeam.luzes_bordo',
    difficulty: 'easy',
  },
  {
    id: 7047,
    subject: 'arrais-amador',
    topic: 'ripeam-regras-de-governo',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Em situação de roda a roda entre duas embarcações a motor, ambas devem:',
    options: { A: 'Guinar para boreste', B: 'Guinar para bombordo', C: 'Manter o rumo sem alteração', D: 'Parar imediatamente', E: 'Acender pirotécnico' },
    correct: 'A',
    explanation: 'Na roda a roda, ambas alteram rumo para boreste para passar por bombordo uma da outra.',
    conceptKey: 'ara.ripeam.roda_a_roda',
    difficulty: 'easy',
  },
  {
    id: 7048,
    subject: 'arrais-amador',
    topic: 'ripeam-regras-de-governo',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Em rumos cruzados entre duas embarcações a motor, deve manobrar quem avista a outra por:',
    options: { A: 'Popa', B: 'Bombordo', C: 'Boreste', D: 'Proa exata', E: 'Través de bombordo exclusivamente' },
    correct: 'C',
    explanation: 'A embarcação que tem a outra por boreste deve se manter fora do caminho.',
    conceptKey: 'ara.ripeam.cruzamento',
    difficulty: 'medium',
  },
  {
    id: 7049,
    subject: 'arrais-amador',
    topic: 'ripeam-regras-de-governo',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Na ultrapassagem, a embarcação que alcança outra deve:',
    options: { A: 'Exigir passagem da embarcação alcançada', B: 'Manter-se fora do caminho da embarcação alcançada', C: 'Apitar e seguir em frente sem cuidado', D: 'Parar a máquina obrigatoriamente', E: 'Ignorar o RIPEAM' },
    correct: 'B',
    explanation: 'Na ultrapassagem, a embarcação que alcança é a responsável por manter-se safa.',
    conceptKey: 'ara.ripeam.ultrapassagem',
    difficulty: 'easy',
  },
  {
    id: 7050,
    subject: 'arrais-amador',
    topic: 'ripeam-regras-de-governo',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Mesmo tendo preferência segundo a regra, uma embarcação deve manter vigilância e agir para evitar colisão porque:',
    options: { A: 'A responsabilidade pela segurança é compartilhada', B: 'A preferência dispensa atenção', C: 'Só o outro é responsável', D: 'O RIPEAM não vale à noite', E: 'A manobra é sempre proibida' },
    correct: 'A',
    explanation: 'A segurança da navegação exige vigilância e ação prudente para evitar abalroamentos.',
    conceptKey: 'ara.ripeam.responsabilidade',
    difficulty: 'medium',
  },
  {
    id: 7051,
    subject: 'arrais-amador',
    topic: 'ripeam-sinais-sonoros',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Sinais sonoros entre embarcações servem para:',
    options: { A: 'Substituir todas as luzes', B: 'Indicar intenções e alertar em determinadas situações', C: 'Medir a distância até a costa', D: 'Informar a maré', E: 'Acionar o GNSS' },
    correct: 'B',
    explanation: 'Os sinais sonoros comunicam intenções de manobra e servem de alerta em condições específicas.',
    conceptKey: 'ara.ripeam.sinais_sonoros_funcao',
    difficulty: 'easy',
  },
  {
    id: 7052,
    subject: 'arrais-amador',
    topic: 'iala-balizamento',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'No sistema IALA Região B, ao demandar um porto vindo do mar, a marca lateral verde indica o lado de:',
    options: { A: 'Bombordo do canal', B: 'Boreste do canal', C: 'Perigo isolado', D: 'Águas seguras', E: 'Canal interditado' },
    correct: 'B',
    explanation: 'Na Região B, verde marca boreste quando se entra no porto vindo do mar.',
    conceptKey: 'ara.iala.verde_boreste',
    difficulty: 'easy',
  },
  {
    id: 7053,
    subject: 'arrais-amador',
    topic: 'iala-balizamento',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'No sistema IALA Região B, a marca lateral encarnada indica o lado de:',
    options: { A: 'Boreste do canal', B: 'Bombordo do canal', C: 'Águas seguras', D: 'Perigo isolado', E: 'Área militar' },
    correct: 'B',
    explanation: 'Na Região B, encarnado marca bombordo na entrada do porto.',
    conceptKey: 'ara.iala.encarnado_bombordo',
    difficulty: 'easy',
  },
  {
    id: 7054,
    subject: 'arrais-amador',
    topic: 'iala-balizamento',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Uma marca de perigo isolado serve para indicar:',
    options: { A: 'Um perigo localizado cercado por águas navegáveis', B: 'O meio do canal seguro', C: 'O limite de uma praia de banho', D: 'Uma estação meteorológica', E: 'Somente a posição de uma marina' },
    correct: 'A',
    explanation: 'A marca de perigo isolado assinala um perigo pontual cercado de águas seguras ao redor.',
    conceptKey: 'ara.iala.perigo_isolado',
    difficulty: 'medium',
  },
  {
    id: 7055,
    subject: 'arrais-amador',
    topic: 'iala-balizamento',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Uma marca de águas seguras normalmente indica:',
    options: { A: 'Perigo submerso não sinalizado', B: 'Água navegável ao redor, como entrada de canal', C: 'Limite de velocidade', D: 'Área de fundeio proibida', E: 'Área de mergulho' },
    correct: 'B',
    explanation: 'Marcas de águas seguras podem indicar meio do canal, aterragens e entradas.',
    conceptKey: 'ara.iala.aguas_seguras',
    difficulty: 'medium',
  },
  {
    id: 7056,
    subject: 'arrais-amador',
    topic: 'vhf',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'O VHF marítimo é usado para:',
    options: { A: 'Somente ouvir música', B: 'Comunicação móvel marítima de rotina e emergência', C: 'Substituir boias de salvatagem', D: 'Navegar sem vigia', E: 'Medir profundidade' },
    correct: 'B',
    explanation: 'O VHF é meio essencial de comunicação entre embarcações e com estações costeiras.',
    conceptKey: 'ara.vhf.funcao',
    difficulty: 'easy',
  },
  {
    id: 7057,
    subject: 'arrais-amador',
    topic: 'vhf',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Em situação de grave e iminente perigo, a chamada adequada no VHF é de:',
    options: { A: 'Routine', B: 'Pan Pan', C: 'Securité', D: 'Mayday', E: 'Roger' },
    correct: 'D',
    explanation: 'Mayday é a chamada internacional de socorro em perigo grave e iminente.',
    conceptKey: 'ara.vhf.mayday',
    difficulty: 'easy',
  },
  {
    id: 7058,
    subject: 'arrais-amador',
    topic: 'vhf',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Uma mensagem de urgência no VHF utiliza a expressão:',
    options: { A: 'Mayday', B: 'Pan Pan', C: 'Securité', D: 'Wilco', E: 'Break' },
    correct: 'B',
    explanation: 'Pan Pan é a chamada de urgência, diferente de socorro e de segurança.',
    conceptKey: 'ara.vhf.panpan',
    difficulty: 'medium',
  },
  {
    id: 7059,
    subject: 'arrais-amador',
    topic: 'vhf',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Uma mensagem de segurança no VHF utiliza a expressão:',
    options: { A: 'Pan Pan', B: 'Mayday', C: 'Securité', D: 'Stand by', E: 'Out' },
    correct: 'C',
    explanation: 'Securité é usada para mensagens de segurança da navegação e avisos importantes.',
    conceptKey: 'ara.vhf.securite',
    difficulty: 'medium',
  },
  {
    id: 7060,
    subject: 'arrais-amador',
    topic: 'vhf',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Em comunicações de rotina, o VHF deve ser utilizado com brevidade e disciplina porque:',
    options: { A: 'O espectro é compartilhado e deve permanecer disponível para tráfego importante', B: 'Quanto mais longo o contato, melhor', C: 'As regras de radiocomunicação não se aplicam à navegação interior', D: 'O uso prolongado aumenta a potência do rádio', E: 'Chamadas curtas são proibidas' },
    correct: 'A',
    explanation: 'A disciplina de comunicações mantém os canais disponíveis e reduz interferências desnecessárias.',
    conceptKey: 'ara.vhf.disciplina',
    difficulty: 'medium',
  },
  {
    id: 7061,
    subject: 'arrais-amador',
    topic: 'estabilidade',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'A distribuição inadequada de peso a bordo pode causar:',
    options: { A: 'Melhora automática da estabilidade', B: 'Adriçamento espontâneo permanente', C: 'Perda de estabilidade e comportamento inseguro', D: 'Redução do vento aparente', E: 'Aumento da potência do motor' },
    correct: 'C',
    explanation: 'Peso mal distribuído altera o equilíbrio, piora movimentos e pode comprometer a segurança.',
    conceptKey: 'ara.estab.distribuicao_peso',
    difficulty: 'easy',
  },
  {
    id: 7062,
    subject: 'arrais-amador',
    topic: 'estabilidade',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Em mau tempo, uma preocupação importante do condutor é evitar:',
    options: { A: 'Excesso de vigilância', B: 'Movimentação desordenada de pessoas e cargas', C: 'Uso de coletes', D: 'Redução de velocidade quando necessária', E: 'Busca de abrigo' },
    correct: 'B',
    explanation: 'Pessoas e cargas se deslocando sem controle podem piorar a estabilidade da embarcação.',
    conceptKey: 'ara.estab.mau_tempo_carga',
    difficulty: 'easy',
  },
  {
    id: 7063,
    subject: 'arrais-amador',
    topic: 'estabilidade',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'O balanço é o movimento de rotação da embarcação em torno do eixo:',
    options: { A: 'Longitudinal', B: 'Transversal', C: 'Vertical', D: 'Magnético', E: 'Propulsor' },
    correct: 'A',
    explanation: 'Balanço corresponde ao rolamento da embarcação em torno do eixo longitudinal.',
    conceptKey: 'ara.movimentos.balanco',
    difficulty: 'medium',
  },
  {
    id: 7064,
    subject: 'arrais-amador',
    topic: 'estabilidade',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'O cabeceio é o movimento da embarcação em torno do eixo:',
    options: { A: 'Longitudinal', B: 'Transversal', C: 'Vertical', D: 'Magnético', E: 'Do mastro' },
    correct: 'B',
    explanation: 'Cabeceio é o movimento de arfagem em torno do eixo transversal.',
    conceptKey: 'ara.movimentos.cabeceio',
    difficulty: 'medium',
  },
  {
    id: 7065,
    subject: 'arrais-amador',
    topic: 'estabilidade',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Caturro é um movimento associado principalmente à:',
    options: { A: 'Guinada da embarcação', B: 'Mudança de maré', C: 'Queima de combustível', D: 'Pintura do casco', E: 'Leitura da bússola' },
    correct: 'A',
    explanation: 'Caturro é um movimento de guinada, isto é, em torno do eixo vertical.',
    conceptKey: 'ara.movimentos.caturro',
    difficulty: 'medium',
  },
  {
    id: 7066,
    subject: 'arrais-amador',
    topic: 'rlesta-normam',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'As normas da Autoridade Marítima e o RLESTA existem para:',
    options: { A: 'Dificultar a navegação amadora', B: 'Promover a segurança do tráfego aquaviário', C: 'Substituir o RIPEAM em todas as situações', D: 'Regular apenas barcos militares', E: 'Dispensar habilitação' },
    correct: 'B',
    explanation: 'O objetivo principal é a segurança do tráfego aquaviário e a prevenção de acidentes.',
    conceptKey: 'ara.normas.finalidade',
    difficulty: 'easy',
  },
  {
    id: 7067,
    subject: 'arrais-amador',
    topic: 'rlesta-normam',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Conduzir embarcação em desacordo com normas de segurança pode gerar:',
    options: { A: 'Apenas advertência verbal entre amigos', B: 'Risco, responsabilidade e sanções administrativas', C: 'Aumento do calado', D: 'Melhor desempenho do motor', E: 'Prioridade automática na navegação' },
    correct: 'B',
    explanation: 'O descumprimento das normas pode gerar acidentes e consequências administrativas e legais.',
    conceptKey: 'ara.normas.consequencias',
    difficulty: 'easy',
  },
  {
    id: 7068,
    subject: 'arrais-amador',
    topic: 'termos-nauticos',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'A linha imaginária que vai da proa à popa, dividindo a embarcação em boreste e bombordo, é o plano:',
    options: { A: 'Transversal', B: 'Longitudinal diametral', C: 'Vertical de través', D: 'Metacêntrico', E: 'De maré' },
    correct: 'B',
    explanation: 'O plano diametral longitudinal divide a embarcação em duas metades laterais.',
    conceptKey: 'ara.termos.plano_diametral',
    difficulty: 'hard',
  },
  {
    id: 7069,
    subject: 'arrais-amador',
    topic: 'direcoes-relativas',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'A região lateral à vante do través recebe o nome de:',
    options: { A: 'Alheta', B: 'Amura', C: 'Popa', D: 'Bochecha', E: 'Costado' },
    correct: 'B',
    explanation: 'Amura é a região entre a proa e o través.',
    conceptKey: 'ara.direcoes.amura',
    difficulty: 'medium',
  },
  {
    id: 7070,
    subject: 'arrais-amador',
    topic: 'direcoes-relativas',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'A região lateral à ré do través é chamada de:',
    options: { A: 'Amura', B: 'Alheta', C: 'Bochecha', D: 'Vante', E: 'Meia-nau' },
    correct: 'B',
    explanation: 'Alheta é a região lateral entre o través e a popa.',
    conceptKey: 'ara.direcoes.alheta',
    difficulty: 'medium',
  },
  {
    id: 7071,
    subject: 'arrais-amador',
    topic: 'navegacao-segura',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Manter vigilância visual e auditiva durante a navegação é importante para:',
    options: { A: 'Atender a um princípio básico de navegação segura', B: 'Substituir o RIPEAM', C: 'Dispensar luzes de navegação', D: 'Eliminar a necessidade de radar', E: 'Aumentar a autonomia do combustível' },
    correct: 'A',
    explanation: 'A vigilância é um princípio básico para perceber riscos e reagir a tempo.',
    conceptKey: 'ara.segura.vigilancia',
    difficulty: 'easy',
  },
  {
    id: 7072,
    subject: 'arrais-amador',
    topic: 'navegacao-segura',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Em área com banhistas e outras atividades náuticas, a condução da embarcação deve ser:',
    options: { A: 'Mais prudente, respeitando áreas seletivas e segurança', B: 'Mais veloz para sair logo da área', C: 'Feita com música alta e sem vigia', D: 'Sem preocupação com esteira', E: 'Com prioridade automática do condutor' },
    correct: 'A',
    explanation: 'Áreas com banhistas e intensa atividade exigem prudência máxima e respeito às áreas seletivas.',
    conceptKey: 'ara.segura.banhistas',
    difficulty: 'easy',
  },
  {
    id: 7073,
    subject: 'arrais-amador',
    topic: 'vela-propulsao',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Em embarcações à vela, o entendimento básico do efeito do vento nas manobras é importante porque:',
    options: { A: 'O vento influencia o governo e a segurança', B: 'A vela não sofre influência do vento', C: 'O leme se torna inútil sempre', D: 'A embarcação passa a ser considerada fundeada', E: 'Dispensa o plano de navegação' },
    correct: 'A',
    explanation: 'O vento é elemento central na propulsão e no comportamento de embarcações à vela.',
    conceptKey: 'ara.vela.vento_manobra',
    difficulty: 'easy',
  },
  {
    id: 7074,
    subject: 'arrais-amador',
    topic: 'propulsao',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'O leme atua principalmente para:',
    options: { A: 'Aumentar a potência do motor', B: 'Controlar a direção da embarcação', C: 'Medir profundidade', D: 'Substituir a âncora', E: 'Distribuir combustível' },
    correct: 'B',
    explanation: 'O leme é o principal dispositivo de governo da embarcação.',
    conceptKey: 'ara.propulsao.leme_funcao',
    difficulty: 'easy',
  },
  {
    id: 7075,
    subject: 'arrais-amador',
    topic: 'navegacao-segura',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Antes de partir, informar a alguém em terra seu destino e previsão de retorno é uma medida:',
    options: { A: 'Dispensável e sem utilidade', B: 'De prudência e segurança', C: 'Somente estética', D: 'Válida apenas para navios', E: 'Proibida em navegação interior' },
    correct: 'B',
    explanation: 'Informar rota e retorno previsto facilita o acionamento de ajuda em caso de atraso ou emergência.',
    conceptKey: 'ara.segura.aviso_terra',
    difficulty: 'easy',
  },
  {
    id: 7076,
    subject: 'arrais-amador',
    topic: 'ripeam-marcas',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'As marcas de navegação complementam as luzes porque permitem identificar situações ou condições da embarcação:',
    options: { A: 'Apenas durante o dia', B: 'Principalmente em períodos de visibilidade diurna', C: 'Somente em nevoeiro', D: 'Somente com radar', E: 'Apenas em mar aberto' },
    correct: 'B',
    explanation: 'Marcas são usadas especialmente de dia para indicar condição e atividade da embarcação.',
    conceptKey: 'ara.ripeam.marcas_dia',
    difficulty: 'medium',
  },
  {
    id: 7077,
    subject: 'arrais-amador',
    topic: 'vhf',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'O uso de um VHF portátil a bordo é útil porque:',
    options: { A: 'Permite comunicação mesmo fora da posição do rádio fixo', B: 'Substitui toda a palamenta', C: 'Dispensa bateria', D: 'Anula as regras do serviço móvel marítimo', E: 'Opera sem qualquer limitação' },
    correct: 'A',
    explanation: 'O portátil amplia a mobilidade na comunicação, mantendo as regras operacionais do serviço.',
    conceptKey: 'ara.vhf.portatil',
    difficulty: 'easy',
  },
  {
    id: 7078,
    subject: 'arrais-amador',
    topic: 'fundeio',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Suspender, em linguagem náutica, significa:',
    options: { A: 'Atracar', B: 'Lançar a âncora', C: 'Virar a embarcação', D: 'Levar a âncora para bordo', E: 'Reduzir a rotação do motor' },
    correct: 'D',
    explanation: 'Suspender é recolher a âncora, preparando a embarcação para sair do fundeadouro.',
    conceptKey: 'ara.fundeio.suspender',
    difficulty: 'medium',
  },
  {
    id: 7079,
    subject: 'arrais-amador',
    topic: 'fundeio',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Fundear significa:',
    options: { A: 'Lançar a âncora e prender a embarcação ao fundo', B: 'Aumentar a velocidade', C: 'Entrar em canal dragado', D: 'Apagar as luzes de bordo', E: 'Acionar o VHF' },
    correct: 'A',
    explanation: 'Fundear é lançar a âncora com a finalidade de manter a embarcação parada em determinado local.',
    conceptKey: 'ara.fundeio.fundear',
    difficulty: 'easy',
  },
  {
    id: 7080,
    subject: 'arrais-amador',
    topic: 'incendio',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Ao perceber princípio de incêndio em equipamento elétrico energizado, é inadequado usar diretamente:',
    options: { A: 'Procedimento compatível com a classe do fogo', B: 'Extintor apropriado', C: 'Água, se houver risco elétrico', D: 'Isolamento da fonte de energia quando possível', E: 'Apoio da tripulação com segurança' },
    correct: 'C',
    explanation: 'Água pode representar risco adicional em incêndios com eletricidade energizada.',
    conceptKey: 'ara.incendio.eletrico',
    difficulty: 'medium',
  },
  {
    id: 7081,
    subject: 'arrais-amador',
    topic: 'primeiros-socorros',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Em caso de mal súbito a bordo, a prioridade inicial é:',
    options: { A: 'Manter a segurança da embarcação, avaliar a vítima e buscar ajuda', B: 'Dar bebida alcoólica', C: 'Abandonar a navegação sem controle', D: 'Ignorar os sinais', E: 'Mover a vítima sem necessidade e sem cuidado' },
    correct: 'A',
    explanation: 'A segurança do conjunto e a avaliação inicial da vítima orientam as próximas ações e o pedido de socorro.',
    conceptKey: 'ara.ps.mal_subito',
    difficulty: 'easy',
  },
  {
    id: 7082,
    subject: 'arrais-amador',
    topic: 'sobrevivencia',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Em caso de abandono, a utilização correta da balsa salva-vidas e sua palamenta é importante porque:',
    options: { A: 'Aumenta as chances de sobrevivência e organização do grupo', B: 'Substitui a necessidade de resgate', C: 'Permite navegar sem rumo indefinidamente com segurança total', D: 'Dispensa água e proteção térmica', E: 'Elimina o efeito do mar e do vento' },
    correct: 'A',
    explanation: 'A balsa e sua palamenta oferecem apoio, proteção e recursos importantes até o socorro.',
    conceptKey: 'ara.sobrevivencia.balsa',
    difficulty: 'medium',
  },
  {
    id: 7083,
    subject: 'arrais-amador',
    topic: 'salvatagem',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Coletes salva-vidas devem ser:',
    options: { A: 'Guardados em local inacessível para não ocupar espaço', B: 'Mantidos em local conhecido e de fácil acesso', C: 'Usados somente por quem não sabe nadar', D: 'Substituídos por boias improvisadas', E: 'Dispensados em águas interiores' },
    correct: 'B',
    explanation: 'Em emergência, o acesso rápido ao colete é fundamental.',
    conceptKey: 'ara.salvatagem.acesso_coletes',
    difficulty: 'easy',
  },
  {
    id: 7084,
    subject: 'arrais-amador',
    topic: 'navegacao-segura',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'O excesso de velocidade em área restrita aumenta principalmente o risco de:',
    options: { A: 'Abalroamento, danos por esteira e perda de controle', B: 'Redução do consumo de combustível', C: 'Melhor comunicação por VHF', D: 'Aumento da flutuação', E: 'Desaparecimento da maré' },
    correct: 'A',
    explanation: 'Em áreas restritas, velocidade excessiva reduz tempo de reação e pode causar danos a terceiros.',
    conceptKey: 'ara.segura.velocidade_restrita',
    difficulty: 'easy',
  },
  {
    id: 7085,
    subject: 'arrais-amador',
    topic: 'ripeam-luzes',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Ao avistar à noite uma luz verde de outra embarcação, isso indica que você está vendo seu lado de:',
    options: { A: 'Bombordo', B: 'Boreste', C: 'Popa', D: 'Mastro', E: 'Fundeio' },
    correct: 'B',
    explanation: 'A luz verde corresponde ao lado de boreste da outra embarcação.',
    conceptKey: 'ara.ripeam.verde_boreste',
    difficulty: 'medium',
  },
  {
    id: 7086,
    subject: 'arrais-amador',
    topic: 'ripeam-luzes',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Ao avistar à noite uma luz encarnada de outra embarcação, você está vendo seu lado de:',
    options: { A: 'Boreste', B: 'Bombordo', C: 'Popa', D: 'Fundeio', E: 'Reboque' },
    correct: 'B',
    explanation: 'A luz encarnada corresponde ao lado de bombordo da outra embarcação.',
    conceptKey: 'ara.ripeam.vermelho_bombordo',
    difficulty: 'medium',
  },
  {
    id: 7087,
    subject: 'arrais-amador',
    topic: 'navegacao-segura',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Navegar sob influência de álcool ou substâncias que reduzam reflexos é:',
    options: { A: 'Aceitável se o tempo estiver bom', B: 'Conduta incompatível com a segurança da navegação', C: 'Permitido em qualquer situação recreativa', D: 'Irrelevante em águas interiores', E: 'Compensado por colete salva-vidas' },
    correct: 'B',
    explanation: 'Álcool e outras substâncias comprometem julgamento, coordenação e tempo de reação.',
    conceptKey: 'ara.segura.alcool',
    difficulty: 'easy',
  },
  {
    id: 7088,
    subject: 'arrais-amador',
    topic: 'navegacao-segura',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Sair para navegar sem material de salvatagem suficiente para todos é:',
    options: { A: 'Aceitável em navegação curta', B: 'Inseguro e contrário à boa prática', C: 'Recomendado em dias quentes', D: 'Irrelevante se houver rádio', E: 'Obrigatório apenas à noite' },
    correct: 'B',
    explanation: 'Todos a bordo devem contar com material de salvatagem adequado.',
    conceptKey: 'ara.segura.salvatagem_todos',
    difficulty: 'easy',
  },
  {
    id: 7089,
    subject: 'arrais-amador',
    topic: 'iala-balizamento',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Uma marca especial é usada, em geral, para indicar:',
    options: { A: 'Somente o bordo seguro do canal', B: 'Perigo isolado submerso sempre', C: 'Área ou particularidade mencionada em documentos náuticos', D: 'Meio do canal principal', E: 'Apenas maré vazante' },
    correct: 'C',
    explanation: 'Marcas especiais destacam áreas ou características específicas previstas em documentos náuticos.',
    conceptKey: 'ara.iala.marca_especial',
    difficulty: 'medium',
  },
  {
    id: 7090,
    subject: 'arrais-amador',
    topic: 'mares',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'A consulta à curva de maré é útil porque ajuda a compreender:',
    options: { A: 'A variação da altura da maré ao longo do tempo', B: 'A cor das boias laterais', C: 'A autonomia do combustível', D: 'A rotação do motor', E: 'A pressão do pneu do reboque' },
    correct: 'A',
    explanation: 'A curva de maré mostra a evolução da altura da água ao longo do período considerado.',
    conceptKey: 'ara.mare.curva',
    difficulty: 'medium',
  },
  {
    id: 7091,
    subject: 'arrais-amador',
    topic: 'meteorologia',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Ventos fortes e mudança no estado do mar exigem do condutor, entre outras medidas:',
    options: { A: 'Reduzir exposição ao risco e considerar busca de abrigo', B: 'Aumentar a lotação a bordo', C: 'Desprezar previsão e observação local', D: 'Retirar material de salvatagem para aliviar peso', E: 'Aumentar o trim pela popa sempre' },
    correct: 'A',
    explanation: 'Em condições adversas, reduzir risco e buscar abrigo podem ser medidas decisivas.',
    conceptKey: 'ara.meteo.abrigo',
    difficulty: 'easy',
  },
  {
    id: 7092,
    subject: 'arrais-amador',
    topic: 'instrumentos',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Confiar apenas em um único equipamento eletrônico de navegação, sem conferência com outros elementos, é:',
    options: { A: 'Boa prática sempre', B: 'Conduta sem risco', C: 'Imprudente, pois equipamentos podem falhar', D: 'Obrigatório pela NORMAM', E: 'Mais seguro do que vigilância' },
    correct: 'C',
    explanation: 'Boas práticas recomendam conferir informações e manter vigilância, pois equipamentos podem falhar.',
    conceptKey: 'ara.instrumentos.redundancia',
    difficulty: 'medium',
  },
  {
    id: 7093,
    subject: 'arrais-amador',
    topic: 'vhf',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Em uma chamada de socorro bem feita no VHF, é importante transmitir posição porque:',
    options: { A: 'Ajuda os meios de socorro a localizar a embarcação', B: 'Serve apenas para registro estatístico', C: 'Substitui o pedido de ajuda', D: 'Evita qualquer obrigação de vigilância', E: 'Dispensa o uso do colete' },
    correct: 'A',
    explanation: 'A posição é informação crítica para o socorro localizar rapidamente a embarcação.',
    conceptKey: 'ara.vhf.posicao_socorro',
    difficulty: 'easy',
  },
  {
    id: 7094,
    subject: 'arrais-amador',
    topic: 'propulsao',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Em manobra, a ação do hélice pode influenciar o comportamento da embarcação, especialmente:',
    options: { A: 'Em baixa velocidade e marcha a ré', B: 'Somente em maré de sizígia', C: 'Apenas com mar calmo absoluto', D: 'Somente em embarcações sem leme', E: 'Nunca' },
    correct: 'A',
    explanation: 'Em manobras lentas e em ré, o efeito do hélice se torna mais perceptível.',
    conceptKey: 'ara.propulsao.efeito_helice',
    difficulty: 'medium',
  },
  {
    id: 7095,
    subject: 'arrais-amador',
    topic: 'navegacao-segura',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'A manutenção preventiva da embarcação é importante porque:',
    options: { A: 'Reduz falhas e aumenta a confiabilidade da operação', B: 'Elimina qualquer risco meteorológico', C: 'Substitui inspeção visual antes da saída', D: 'Dispensa checar combustível', E: 'Torna desnecessário material de salvatagem' },
    correct: 'A',
    explanation: 'A manutenção preventiva reduz o risco de falhas durante a navegação.',
    conceptKey: 'ara.segura.manutencao',
    difficulty: 'easy',
  },
  {
    id: 7096,
    subject: 'arrais-amador',
    topic: 'incendio',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Uma forma de prevenir incêndios a bordo é:',
    options: { A: 'Improvisar instalações elétricas', B: 'Armazenar combustível sem cuidado', C: 'Inspecionar sistemas e evitar fontes de ignição indevidas', D: 'Fumar próximo ao abastecimento', E: 'Ignorar cheiro de queimado' },
    correct: 'C',
    explanation: 'Prevenção depende de boas práticas, inspeção e eliminação de riscos de ignição.',
    conceptKey: 'ara.incendio.prevencao',
    difficulty: 'easy',
  },
  {
    id: 7097,
    subject: 'arrais-amador',
    topic: 'sobrevivencia',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Em situação de emergência, manter a calma e organizar funções entre os tripulantes ajuda porque:',
    options: { A: 'Reduz a eficiência', B: 'Melhora a resposta e evita desordem', C: 'É inútil em embarcações pequenas', D: 'Só funciona com rádio', E: 'Substitui o uso do colete' },
    correct: 'B',
    explanation: 'Organização e calma aumentam a eficácia das ações de emergência.',
    conceptKey: 'ara.sobrevivencia.organizacao',
    difficulty: 'easy',
  },
  {
    id: 7098,
    subject: 'arrais-amador',
    topic: 'salvatagem',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'O material de salvatagem deve ser conhecido pela tripulação porque:',
    options: { A: 'Em emergência não há tempo para descobrir como usar', B: 'Serve apenas para inspeção visual', C: 'Só o condutor pode tocar', D: 'Não precisa estar acessível', E: 'É item decorativo' },
    correct: 'A',
    explanation: 'Em situações de emergência, o uso correto e rápido do material pode ser decisivo.',
    conceptKey: 'ara.salvatagem.conhecimento_uso',
    difficulty: 'easy',
  },
  {
    id: 7099,
    subject: 'arrais-amador',
    topic: 'vhf',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Ao terminar uma comunicação de rotina no VHF, é boa prática:',
    options: { A: 'Manter o canal ocupado conversando sem necessidade', B: 'Encerrar de forma clara e liberar o canal', C: 'Repetir toda a mensagem várias vezes sem motivo', D: 'Trocar para canal não combinado sem avisar', E: 'Desligar o rádio durante a navegação' },
    correct: 'B',
    explanation: 'Disciplina de rádio inclui mensagens objetivas e liberação do canal após o contato.',
    conceptKey: 'ara.vhf.encerramento',
    difficulty: 'easy',
  },
  {
    id: 7100,
    subject: 'arrais-amador',
    topic: 'revisao-geral',
    year: 2026,
    exam: 'Simulado Arrais Amador',
    verified: true,
    statement: 'Entre estudar teoria, treinar manobras e respeitar normas de segurança, a melhor preparação para o Arrais-Amador envolve:',
    options: { A: 'Somente decorar nomes de peças', B: 'Combinar conhecimento teórico, prática supervisionada e prudência', C: 'Apenas usar equipamentos eletrônicos', D: 'Navegar sem planejamento para ganhar experiência', E: 'Ignorar meteorologia e marés' },
    correct: 'B',
    explanation: 'A habilitação exige formação equilibrada entre teoria, prática e segurança operacional.',
    conceptKey: 'ara.preparo.integrado',
    difficulty: 'easy',
  },
];
